
version: 0.0

Resources:

  - myLambdaFunction:

      Type: AWS::Lambda::Function

      Properties:

        Name: "aws-graphql"

        Alias: "aws-graphql"

        CurrentVersion: "1"

        TargetVersion: "2"

Hooks:

  - BeforeAllowTraffic: "LambdaFunctionToValidateBeforeTrafficShift"

  - AfterAllowTraffic: "LambdaFunctionToValidateAfterTrafficShift"
